import { ILabels  } from '../engine/stores/Labels.store';

export const DOCTORTILLA_LABELS: ILabels = {
    'es': {
    },
    'en': {
        'AGAIN': 'Again...',
        'ALL_READY_FIND_BILI': 'All is solved now! Let me grab Bili and we\'ll start.',
        'ASK_ABOUT_COSTUME': 'Tell me more about that missing costume.',
        'BARELY_TASTED_LIKE_DRUG': 'Well, it barely tasted like drugs...',
        'BURP': 'Burp!',
        'FIRST_ANGEL_CABLE' : 'First, we need a cable to plug Angel\'s amp',
        'FOUND_THE_CABLE': 'I found a cable!',
        'GOT_THE_COSTUME': 'I just made a costume for you.',
        'GULP_GULP_GULP': 'Gulp\n   Gulp\n      Gulp',
        'HAVE_A_DRINK_SANTI': 'Hey Santi, here, have this drink.',
        'HAVE_YOU_SEEN_BILI': 'Mmm, I\'m missing Bili, where is he?',
        'HE_IS_OUT_SMOKING': 'He\'s outside, drinking and smoking. If we let him there too much time he\'ll be drunk as a skunk',
        'HOW_IS_BILI_DOING': 'How is Bili doing, by the way?',
        'I_AM_NOT_GOING_TO_ASK_WHERE_THIS_COMES_FROM': 'I\'m not going to ask where you got this from.',
        'I_AM_STATRING_TO_FEEL_READY_TO_PLAY': 'It\'s weird, I am suddendly starting to feel ready to play.',
        'IT_IS_A_LONG_TIME_TRADITION_THAT_WE_ALL_DRESSED_UP': 'It is a tradition that started long time ago, dressing up for our concerts...',
        'IT_WAS_COWBOY_COSTUME': 'It was a cowboy costume, man. A cool one.',
        'LATE_FOR_CONCERT': 'Man I am two hours late to my own concert.',
        'LET_S_SAY_I_HAVE_MY_SOURCES': 'Let\'s say I have my sources...',
        'LETS_FIX_THIS_MESS': 'OK, let\'s see if I can fix this disaster.',
        'MAN_YOU_SHOULD_KNOW_THIS': 'Man, you should know this, you started it!',
        'MINE_WAS_WAY_BETTER': 'Mine was WAY better.',
        'MMM_A_REFRESHING_BEVERAGE': 'Mmm a refreshing beverage! Thanks!',
        'OK_I_LL_PUT_IT_ON': 'Ok, boss, I\'ll put it on.',
        'PROBLEMS_I_AM_OUT': 'Problems? Complications? I\'m outta here man...',
        'PROBLEMS_LET_ME_HELP': 'Problems? Please tell me more, dear friends.',
        'READY_TO_PLAY': 'Hey guys! Ready to rock?!',
        'SECOND_JUAN_COSTUME': 'Second, we need a costume for Juan, he forgot his at home.',
        'SO_PLEASE_FIND_ME_SOMETHING_ELEGANT_I_CAN_USE': 'So please find a really elegant costume that lives up to my expectations',
        'SO_WE_SOMEHOW_DISTRACT_THE_ATTENTION': '... so we distract people from the fact that we don\'t know how to play.',
        'SURE_BOSS': 'Yes, sure boss!',
        'TALK_TO_YOU_LATER': 'I have to go, see you later!',
        'THAT_IS_A_STUPID_COSTUME': 'Well, that is a stupid costume if I ever saw one.',
        'THAT_S_THE_SPIRIT': 'That\'s the spirit!',
        'THE_OTHERS_WILL_BE_READY': 'But I am sure the rest of the band will be ready, let\'s talk to them.',
        'THERE_ARE_SOME_PROBLEMS_1': 'Actually some small problems have arised...',
        'THERE_ARE_SOME_PROBLEMS_2': '... really minor complications ...',
        'THERE_ARE_SOME_PROBLEMS_3': '... a CRAZY MESS',
        'THIRD_SANTI_SHY': 'And third, Santi just got shy. He refuses to play...',
        'VINTAGE_PREMIUM_COSTUME': 'A vintage, really premium costume I must say',
        'WE_HAVE_THREE_PROBLEMS': 'We basically we have three problems...',
        'WELL_I_HAD_AN_AWESOME_COSTUME': 'Well I had an awesome costume, you know?',
        'WHY_COSTUMES': 'Why are we all dressed up anyhow?',
        'YOU_BETTER_PUT_IT_ON': 'You better put it one before I get angry',
        'YOU_STOLE_IT': 'You stole it, right?'
    }
};
