import { ILabels  } from '../engine/stores/Labels.store';

export const DOCTORTILLA_LABELS: ILabels = {
    'es': {
    },
    'en': {
        'A_BROOM_THE_PERFECT_CLEANING_INSTRUMENT': 'A broom, the perfect cleaning instrument.',
        'A_RANCID_AND_GREASY_SANDWHICH': 'A rancid and GREASY sandwhich.',
        'AGAIN': 'Again...',
        'ALL_READY_FIND_BILI': 'All is solved now! Let me grab Bili and we\'ll start.',
        'AND_EXPENSIVE': '... and expensive.',
        'ARGH': 'Argh!',
        'ASK_ABOUT_CABLE': 'Where do I find a cable now, you lazy bastards?',
        'ASK_ABOUT_COSTUME': 'Tell me more about that missing costume.',
        'ASK_ABOUT_SANTI': 'What\'s the matter with you Santi?',
        'BACKSTAGE': 'backstage',
        'BACKYARD': 'backyard',
        'BARELY_TASTED_LIKE_DRUG': 'Well, it barely tasted like drugs...',
        'BEAUTIFUL_SOMETHING': 'That is a beautiful something.',
        'BILI_MUST_BE_OUT_THERE_SMOKING': 'Bili must be out there smoking.',
        'BOCADILLO': 'bacon sandwhich',
        'BURP': 'Burp!',
        'BROOM': 'broom',
        'CABLE': 'cable',
        'CANNOT_PICK_A_DOOR_UP': 'I obviously cannot pick the door up. I would destroy the building.',
        'CLONK': 'Clonk\n   clonk\n      clonk',
        'COCONUT': 'coconut',
        'COOL_NOW_I_SHOULD_GIVE_IT_TO_THE_GUYS': 'Cool, now I should give that to the guys.',
        'COMPARE_COMPRAME_UN_COCO': 'A coconut, rough skin, delicious content.',
        'DOES_IT_LOOK_LIKE_A_PAIR_OF_TITS': 'Does it look like a pair of tits?',
        'DOOR_TO_BACKSTAGE': 'door to backstage',
        'DOOR_TO_BACKYARD': 'door to backyard',
        'DOOR_TO_STAGE': 'door to stage',
        'DOOR_TO_STREET': 'door to street',
        'DRUGS_ARE_BAD': '... yeah man drugs are really bad ...',
        'FINALLY_I_GOT_THE_CABLE': 'Finally I got the cable!',
        'FIRST_ANGEL_CABLE' : 'First, we need a cable to plug Angel\'s amp.',
        'FIRST_I_NEED_TO_GET_THE_BAND_READY' : 'First I need to get the band ready.',
        'FOUND_THE_CABLE': 'I found a cable!',
        'GLASS': 'glass',
        'GOT_THE_COSTUME': 'I just made a costume for you.',
        'GULP_GULP_GULP': 'Gulp\n   Gulp\n      Gulp',
        'HAVE_A_DRINK_SANTI': 'Hey Santi, here, have this drink.',
        'HAVE_YOU_SEEN_BILI': 'Mmm, I\'m missing Bili, where is he?',
        'HI_DOOR_HOW_ARE_YOU_TODAY': 'Hi door! How are you today?',
        'HI_THERE': 'Hi there.',
        'HE_IS_OUT_SMOKING': 'He\'s outside, drinking and smoking. If we let him there too much time he\'ll be drunk as a skunk.',
        'HOW_IS_BILI_DOING': 'How is Bili doing, by the way?',
        'I_ALREADY_HAVE_IT': 'I already have it.',
        'I_ALREADY_PUSHED_IT': 'I already pushed it, I don\'t wanna over do it.',
        'I_AM_NOT_GOING_TO_ASK_WHERE_THIS_COMES_FROM': 'I\'m not going to ask where you got this from.',
        'I_AM_STATRING_TO_FEEL_READY_TO_PLAY': 'It\'s weird, I am suddendly starting to feel ready to play.',
        'I_BET_THIS_DUST_CAN_MAKE_SOMEBODY_LESS_SHY': 'I bet this "dust" can make "somebody" less shy',
        'I_CAN_HEAR_THE_CROWD_WAITING_FOR_US': 'I can hear the crowd waiting for us, good thing this door is protecting us.',
        'I_CANT_MOVE_THAT': 'I can\'t move that.',
        'I_CANT_DO_THAT': 'I can\'t do that.',
        'I_COULD_MAKE_A_WIG_WITH_THIS': 'I think I could make a blonde wig with this.',
        'I_DONT_KNOW_HOW_TO_DO_THAT': 'I don\'t know how to do that.',
        'I_DONT_KNOW_HOW_TO_USE_THAT_WITH_VENDING_MACHINE': 'I don\t know how to use that with a vending machine...',
        'I_HAVE_A_CONCERT_TO_PLAY': 'I have a concert to play!',
        'I_HAVE_BETTER_THINGS_TO_DO_THAN_TALKING': 'I have better things to do than talking to objects.',
        'I_HAVE_TO_PICK_IT_UP_FIRST': 'I have to pick it up first.',
        'I_SHOULD_PROBABLY_MIX_IT_IN_A_GLASS': 'I should probably mix it in a glass.',
        'I_THINK_I_CAN_OPEN_IT_AND_TAKE_THE_BACON': 'I think I can open it and take the bacon.',
        'I_WOULD_DO_IT_MYSELF': 'I would do it myself, but it is kind of illegal...',
        'I_WOULDNT_KNOW_WHAT_TO_SAY': 'I wouldn\'t know what to say.',
        'IF_I_COULD_PUT_GREASE_BELOW': 'If I could just put some grease below it...',
        'IMPLIES_MOVEMENT': '... and it implies a certain ammount of effort and movement.',
        'IT_IS_A_LONG_TIME_TRADITION_THAT_WE_ALL_DRESSED_UP': 'It is a tradition that started long time ago, dressing up for our concerts...',
        'IT_IS_ALREADY_CLOSED': 'It is already closed.',
        'IT_IS_ALREADY_FULL': 'It is already full.',
        'IT_IS_INDEED_A_GLASS': 'It is indeed a glass.',
        'IT_IS_STUCK_BEHIND_THE_VENDING_MACHINE': 'It is stuck behind the vending machine, I need to move it somehow.',
        'IT_WAS_COWBOY_COSTUME': 'It was a cowboy costume, man. A cool one.',
        'IS_SOMEHOW_DANGEROUS': '... marginally dangerous, I would say...',
        'JUST_STEAL_ONE': 'Don\'t know man, just steal one somewhere.',
        'LATE_FOR_CONCERT': 'Man I am two hours late to my own concert.',
        'LET_S_SAY_I_HAVE_MY_SOURCES': 'Let\'s say I have my sources...',
        'LETS_FIX_THIS_MESS': 'OK, let\'s see if I can fix this disaster.',
        'MADE_OF_METAL_RUST_AND_STICKY_STUFF': 'Door. Composition: 80% metal, 15% rust, 5% unidentified sticky stuff.',
        'MAN_YOU_SHOULD_KNOW_THIS': 'Man, you should know this, you started it!',
        'MINE_WAS_WAY_BETTER': 'Mine was WAY better.',
        'MMM_A_REFRESHING_BEVERAGE': 'Mmm a refreshing beverage! Thanks!',
        'NICE_IT_WILL_SLIDE_REALLY_WELL_NOW': 'Nice, it will slide really well now...',
        'NICE_OBJECT': 'Nice object.',
        'NICE_SAFE_DOOR': 'It is door. Useful to make people feel safe and cozy inside of places.',
        'NOPE_I_CANNOT_GO_TO_THE_STREET': 'Nope, I can\'t go to the street yet.',
        'NOPE_I_CANNOT_GO_TO_THE_STAGE': 'Nope, I can\'t go to the stage yet.',
        'NOPE_I_DONT_WANT_TO_TAKE_BILIS_BALLOON': 'Nope, I don\'t wanna take Bili\'s balloon. He needs it for his costume.',
        'NOT_SAFE_HAVING_SCISSORS_AROUND_MUSICIANS': 'Not safe having scissors around musicians.',
        'NOT_SAYING_WE_SHOULD_USE_THEM': 'I am not saying we should used them, but...',
        'OH_LOOK_AT_THAT': 'Oh! Look at that.',
        'OK_I_LL_PUT_IT_ON': 'Ok, boss, I\'ll put it on.',
        'PROBLEMS_I_AM_OUT': 'Problems? Complications? I\'m outta here man...',
        'PROBLEMS_LET_ME_HELP': 'Problems? Please tell me more, dear friends.',
        'READY_TO_PLAY': 'Hey guys! Ready to rock?!',
        'REALLY_USEFUL_TO_PUT_LIQUIDS_INSIDE': 'Really useful to put liquids or other substances inside.',
        'REST_OF_THE_BAND': 'rest of the band',
        'SECOND_JUAN_COSTUME': 'Second, we need a costume for Juan, he forgot his at home.',
        'SCISSORS': 'scissors',
        'SHE_IS_SHY_DOESNT_WANT_TO_TALK_TO_ME': 'She is shy, doesn\'t want to talk with me today.',
        'SHINY_AND_SHARP': 'Shiny and sharp!',
        'SO_PLEASE_FIND_ME_SOMETHING_ELEGANT_I_CAN_USE': 'So please find a really elegant costume that lives up to my expectations.',
        'SO_WE_SOMEHOW_DISTRACT_THE_ATTENTION': '... so we distract people from the fact that we don\'t know how to play.',
        'SOME_CULTURES_USED_DRUGS': 'You know, some cultures used drugs to encourage warriors...',
        'SURE_BOSS': 'Yes, sure boss!',
        'SUSPICIOUS_DUST': 'suspicious dust',
        'TALK_TO_YOU_LATER': 'I have to go, see you later!',
        'THAT_CANNOT_BE_CLOSED': 'That cannot be closed.',
        'THAT_CANNOT_BE_OPENED': 'That cannot be opened.',
        'THAT_IS_A_HUGE_BALLOON_QUITE_SCARY_IF_IT_EXPLODES': 'That is a huge balloon, it would be quite scary if it exploded.',
        'THAT_IS_A_STUPID_COSTUME': 'Well, that is a stupid costume if I ever saw one.',
        'THAT_IS_MY_BAND_1': 'That is my band. They may be lazy and not specially skilled, but they are nice people.',
        'THAT_IS_MY_BAND_2': 'Oh my, what a band! The best from the best!',
        'THAT_IS_MY_BAND_3': 'Look at them, so peaceful, not moving a finger...',
        'THAT_S_SOME_HIGHLY_SUSPICIOUS_WHITE_POWDER': 'That\'s some highly suspicious white powder.',
        'THAT_S_THE_DOOR_TO_GO_BACK_TO_THE_BACKSTAGE': 'That\'s the door to go BACK to the BACKstage.',
        'THAT_S_THE_SPIRIT': 'That\'s the spirit!',
        'WISE_PURCHASE': 'That was a wise purchase.',
        'THE_FLOOR_IS_STICKY': 'The floor is so sticky it is impossible to move it.',
        'THE_OTHERS_WILL_BE_READY': 'But I am sure the rest of the band will be ready, let\'s talk to them.',
        'THERE_ARE_SOME_PROBLEMS_1': 'Actually some small problems have arised...',
        'THERE_ARE_SOME_PROBLEMS_2': '... really minor complications ...',
        'THERE_ARE_SOME_PROBLEMS_3': '... a CRAZY MESS.',
        'THIRD_SANTI_SHY': 'And third, Santi just got shy. He refuses to play...',
        'THIS_CABLE_COULD_BE_USEFUL': 'This cable could be useful, maybe I can "borrow" it.',
        'VENDING_MACHINE': 'vending machine',
        'VINTAGE_PREMIUM_COSTUME': 'A vintage, really premium costume I must say.',
        'WE_DONT_REHEARSE_ENOUGH': 'Man, we haven\'t practiced enough, we are not ready to play!',
        'WE_HAVE_THREE_PROBLEMS': 'Basically we have three problems...',
        'WE_HAVENT_PRACTISED_SINCE_2012': 'I think last rehearsal was in 2012.',
        'WELL_I_HAD_AN_AWESOME_COSTUME': 'Well I had an awesome costume, you know?',
        'WHAT_CAN_WE_DO_GUYS': 'What can we do guys? Any ideas?',
        'WHY_COSTUMES': 'Why are we all dressed up anyhow?',
        'YOU_BETTER_PUT_IT_ON': 'You better put it one before I get angry.',
        'YOU_ARE_A_COWARD_MAN_WE_HAVE_COSTUMES': 'Don\'t be a pussy man... We have our costumes, people just won\'t pay attention to the music.',
        'YOU_STOLE_IT': 'You stole it, right?'
    }
};
